ERROR:root:Traceback (most recent call last):
  File "htdocs/info.cgi", line 50, in <module>
    solve()
  File "htdocs/info.cgi", line 15, in solve
    name = "姓名: " + formdata['name'].value
  File "/usr/lib/python2.7/cgi.py", line 546, in __getitem__
    raise KeyError, key
KeyError: 'name'

ERROR:root:Traceback (most recent call last):
  File "htdocs/info.cgi", line 50, in <module>
    solve()
  File "htdocs/info.cgi", line 15, in solve
    name = "姓名: " + formdata['name'].value
  File "/usr/lib/python2.7/cgi.py", line 546, in __getitem__
    raise KeyError, key
KeyError: 'name'

ERROR:root:Traceback (most recent call last):
  File "htdocs/info.cgi", line 50, in <module>
    solve()
  File "htdocs/info.cgi", line 15, in solve
    name = "姓名: " + formdata['name'].value
  File "/usr/lib/python2.7/cgi.py", line 546, in __getitem__
    raise KeyError, key
KeyError: 'name'

